### ISSUE TITLE
A way to read strings?

### ISSUE THREAD

**Issue by lsaa** [Tommoa/rs-process-memory#3]
I was able to read strings using this
```
// Oh god oh fuck I'm sorry I need to find a better way to do this
pub fn try_read_string(handle: process_memory::ProcessHandle, mut starting_offsets: Vec<usize>, buffer_size : i32) -> Result<String, std::io::Error> {
    //Read String 4 in 4 bytes
    use process_memory::*;
    use std::mem::transmute;
    let number_of_passes: f32 = buffer_size as f32 / 4.0;

    let last_offset = starting_offsets.pop().unwrap();
    let offsets: Vec<usize> = starting_offsets.clone();

    let mut string_return = String::new();
    'outer: for i in 0..(number_of_passes.ceil() as i32) {
        let player_name = DataMember::<u32>::new_offset(handle, [offsets.clone(), vec![last_offset + (4*i as usize)]].concat());
        let bytes: [u8; 4] = unsafe { transmute(player_name.read()?.to_le()) };
        for byte in bytes.iter() {
            if *byte != 0x0_u8 {
                string_return.push(*byte as char);
            } else {
                break 'outer;
            }
        }
    }

    return Ok(string_return);
}
```
it works but is there a way to do it without all this?

**Comment by Tommoa** [comment]
The reason why this crate doesn't define methods for copying strings (although it would be very useful) is because strings can vary even on the same platform. e.g. Rust uses (len, ptr) for strings, C/C++ uses a null byte, and this isn't even getting into small string optimizations that C++ uses. As such, its somewhat hard for me to recommend a way to read a string without necessarily knowing more about the layout of the string.

My first question would be, what kind of string is it? Is it an ASCII string, or a UTF-8 string, or a UTF-16 string, or a UTF-32 string? Depending on which one it is, you may need to change the size of your buffer.

Second question would be, if you overrun the string, are you likely to run out of allocated memory? If you're on Windows, calls to `ReadProcessMemory` (which this crate does under the hood) will fail if the entire region isn't readable, which could mean that you cut off your string early or return with an error that you otherwise shouldn't.

With these two things in mind, my suggested implementation for a UTF-8 string would be as follows:
```rust
pub fn try_read_string(handle: process_memory::ProcessHandle, starting_offsets: Vec<usize>) -> Result<String, std::io::Error> {
        let mut offset = handle.get_offset(&starting_offsets);
        let mut parts = Vec::<u8>::new(); 
        let mut byte = [0u8; 1];
        loop {
            handle.copy_address(offset, &mut byte)?;
            if byte[0] == 0 {
                break;
            }
            offset += 1;
            parts.push(byte[0]);
        }
        String::from_utf8(parts).map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))
}
```

This of course has the problem of being relatively slow as you have to get a single byte at a time. If you are able to get the length of the entire string, then I'd suggest allocating `parts` to be the same size as the length and then just calling `handle.copy_address()` once.

**Comment by lsaa** [comment]
Thanks for the quick response, the string I'm looking at are std::String (C++) so I can find the length and that makes it a lot easier. I'll give the allocation and copying a shot.

**Comment by lsaa** [comment]
Yeah that worked

`
pub fn try_read_std_string_utf8(handle: process_memory::ProcessHandle, starting_offsets: Vec<usize>) -> Result<String, std::io::Error> {
    use process_memory::*;
    let mut offset = DataMember::<u8>::new_offset(handle, starting_offsets);
    let len_off = DataMember::<i32>::new_offset(handle, vec![offset.get_offset()? - 8]);
    let len = len_off.read()? as usize;
    let mut bytes = vec![0_u8; len];
    handle.copy_address(offset.get_offset()?, &mut bytes)?;
    String::from_utf8(bytes).map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))
}
`

This is what it ended up like, couldn't find "handle.get_offset()" so I just did the offset the only way I know.
You can close the issue now, you made it clear why it is the way it is and gave a serviceable alternative, thanks man.

**Comment by Tommoa** [comment]
`get_offset()` is a part of the [`CopyAddress`](https://docs.rs/process-memory/0.4.0/process_memory/trait.CopyAddress.html) trait.

Good to know you were able to do it!
