### ISSUE TITLE
Cannot create ProcessHandle on macOS

### ISSUE THREAD

**Issue by kramer425** [Tommoa/rs-process-memory#8]
Hi, I'm trying to connect to the `Calculator` app and I'm seeing `Undefined error: 0 (os error 0)` while running this program with sudo. 

```rust 
use std::{env, error::Error};
use process_memory::*;

struct InputPid {
    pid: u32
}

impl InputPid {
    fn new(args: &[String]) -> Result<InputPid, Box<dyn Error>> {
        if args.len() < 2 {
            return Err("Please enter a pid".into());
        }
        let arg = &args[1];
        let pid: u32 = arg.trim().parse().map_err(|_e| format!("Please enter a pid - got: {}", arg))?;
        Ok(InputPid { pid })
    }
}

fn main() {
    let args: Vec<String> = env::args().collect();

    let input_pid = InputPid::new(&args).unwrap();

    println!("{}", input_pid.pid);
    
    let handle: ProcessHandle = (input_pid.pid as Pid).try_into_process_handle()
        .map_err(|e| format!("Could not connect to pid {}: {}", input_pid.pid, e)).unwrap()
        .set_arch(Architecture::Arch64Bit);
}
```

Any ideas how to debug this? I'm on `macOS 10.15.7`. Thanks

**Comment by Tommoa** [comment]
Hm, I've copied your code but I can't seem to replicate this on macOS 11.2.3.

I get the same error when running without `sudo`, though I have no issues when running with `sudo`. My best guess is that you probably have all system integrity protection options on, whilst I have [some of them disabled so I can run `yabai`](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection).

I think that with SIP enabled, you can only attach to processes that are in the same process group or that you have spawned.

**Comment by kramer425** [comment]
Thanks! That did the trick

**Comment by oatmealine** [comment]
Running into this on macOS 11.7.11. Running w/o `sudo` gives me `No such process (os error 3)` on `try_into_process_handle`, running w/ `sudo` gives me the aforementioned `Undefined error: 0 (os error 0)` on `DataMember::read`. Disabling SIP did not make a difference.

**Comment by oatmealine** [comment]
Correction: the `Undefined error: 0 (os error 0)` (which I later identified was actually `(os/kern) failure` when put through `mach_error_string`) which I presumed was happening on `DataMember::read` is instead happening on `try_into_process_handle` immediately after a write. The write appears to be successful, but the memory stays unmodified. This may be an unrelated issue, but I wouldn't be certain what to file this as (and this does not occur on Linux with identical code)

EDIT: nevermind, this was actually an issue with me casting the process handle tuple's first argument into a PID, because that had worked on Linux to retrieve the PID back from the handle, my bad; though while debugging this, I did find a more elegant solution than disabling SIP or running as root:
```
codesign -s - --entitlements entitlements.plist -f target/debug/yourprogram
```
where `entitlements.plist` is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.debugger</key>
    <true/>
</dict>
</plist>
```
